#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DBD-SQLite2
Version  : 0.37
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/DBD-SQLite2-0.37.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/DBD-SQLite2-0.37.tar.gz
Summary  : 'Self Contained RDBMS in a DBI Driver (sqlite 2.x)'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-DBD-SQLite2-lib
Requires: perl-DBD-SQLite2-man
BuildRequires : perl(DBI)

%description
DBD::SQLite2
============
SQLite is a small fast embedded SQL database engine.
DBD::SQLite2 embeds that database engine into a DBD driver, so
if you want a relational database for your project, but don't
want to install a large RDBMS system like MySQL or PostgreSQL,
then DBD::SQLite2 may be just what you need.

%package lib
Summary: lib components for the perl-DBD-SQLite2 package.
Group: Libraries

%description lib
lib components for the perl-DBD-SQLite2 package.


%package man
Summary: man components for the perl-DBD-SQLite2 package.
Group: Default

%description man
man components for the perl-DBD-SQLite2 package.


%prep
%setup -q -n DBD-SQLite2-0.37

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/DBD/SQLite2.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/DBD/getsqlite.pl

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/DBD/SQLite2/SQLite2.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/DBD::SQLite2.3
